name: macOS App Bundle

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore DDCImprover.Avalonia/DDCImprover.Avalonia.csproj -r osx-x64
    - name: Build, Publish & Bundle
      run: dotnet msbuild DDCImprover.Avalonia/DDCImprover.Avalonia.csproj -t:BundleApp -p:RuntimeIdentifier=osx-x64 -p:IsMac=true -p:Configuration=Debug
    - name: Create Bundle Directory
      run: mkdir AppBundle
    - name: Copy Bundle
      run: cp -ar DDCImprover.Avalonia/bin/Debug/netcoreapp3.1/osx-x64/publish/DDC\ Improver.app AppBundle
    - name: Upload App Bundle Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DDCImprover
        path: AppBundle
