name: macOS App Bundle

on:
  push:
    branches: [ master ]

jobs:
  bundle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore DDCImprover.Avalonia/DDCImprover.Avalonia.csproj -r osx-x64
    - name: Build, Publish & Bundle
      run: dotnet msbuild DDCImprover.Avalonia/DDCImprover.Avalonia.csproj -t:BundleApp -p:RuntimeIdentifier=osx-x64 -p:IsMac=true -p:Configuration=Release -p:PublishTrimmed=true
    - name: Copy Bundle
      run: cp -ar DDCImprover.Avalonia/bin/Release/netcoreapp3.1/osx-x64/publish/DDC\ Improver.app .
    - name: Set Bundle Permissions
      run: chmod 755 DDC\ Improver.app
    - name: Make the Executable Executable
      run: chmod +x DDC\ Improver.app/Contents/MacOS/DDCImprover
    - name: Create Zip File
      run: zip -r DDCImprover.zip DDC\ Improver.app/
    - name: Upload App Bundle Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DDCImprover
        path: DDCImprover.zip
