name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Change To Avalonia
      run: cd DDCImprover.Avalonia
    - name: Install dependencies
      run: dotnet restore -r osx-x64
    - name: Build, Publish & Bundle
      run: dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64 -p:IsMac=true -p:Configuration=Debug
    - name: Upload App Bundle Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DDCImprover
        path: bin\Debug\netcoreapp3.1\osx-x64\publish\DDC Improver.app
